# Async Exceptions

Async functions can throw exceptions.
